services:
  db:
    image: postgres:12
    ports:
      - "5433:5432"
    expose:
      - 5433
    env_file:
      - .env
    networks:
      - pwp-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  pwp-network: